[package]
name = "nostr-sdk"
version = "0.14.2"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "rust"]

[features]
default = ["all-nips"]
sqlite = ["dep:nostr-sdk-sqlite"]
blocking = ["nostr/blocking"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip13", "nip19", "nip26"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip13 = ["nostr/nip13"]
nip19 = ["nostr/nip19"]
nip26 = ["nostr/nip26"]

[dependencies]
futures-util = "0.3"
log = "0.4"
nostr = { version = "0.14", path = "../nostr" }
nostr-sdk-sqlite = { version = "0.14", path = "../nostr-sdk-sqlite", optional = true }
once_cell = "1"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.23.4"
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
webpki-roots = "0.22.6"

[dev-dependencies]
env_logger = "0.10"

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "sqlite"
required-features = ["all-nips", "sqlite"]

[[example]]
name = "blocking"
required-features = ["all-nips", "blocking"]